package com.acme.dept.interestrates.acmebank_interestrates;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class interestratesDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public interestratesDO() {
    }

}